// Asset library pools — bridges assets/manifest.json into the Context Resolver.
//
// The manifest is generated by `node tools/build-asset-manifest.mjs` from the
// scanned library. Selection follows the same determinism contract as the rest
// of the resolver: hash01(featureId + poolKey) → pickWeighted, so an OSM
// feature always resolves to the same asset, but neighboring features vary.

import manifest from '../../assets/manifest.json'
import { hash01, pickWeighted } from './resolve'

export interface LibraryAsset {
  id: string
  path: string
  semantic: string
  role: string
  style: string
  osmTags: string[]
  internalTags: string[]
  referenceOnly: boolean
  sizeMeters: { x: number; y: number; z: number } | null
  groundOffsetY: number
  triangles: number
  bytes: number
  lods: string[]
  materials: unknown[]
  textures: unknown[]
  source: string
  license: string
  flags: string[]
}

interface Pool {
  osmTag: string
  style: string
  semantic: string
  referenceOnly: boolean
  // normalizeScale:true marks a non-metric source asset that must be scaled to
  // real bounds on placement (see normalizeScale / the wide default clamp).
  entries: { id: string; weight: number; normalizeScale?: boolean }[]
}

const assetsById = new Map<string, LibraryAsset>(
  (manifest.assets as LibraryAsset[]).map(a => [a.id, a]),
)
const pools = manifest.pools as Record<string, Pool>

export function libraryAsset(id: string): LibraryAsset | undefined {
  return assetsById.get(id)
}

/** All pools that can satisfy an OSM tag (one per style). */
export function poolsForTag(osmTag: string): { key: string; pool: Pool }[] {
  return Object.entries(pools)
    .filter(([, p]) => p.osmTag === osmTag)
    .map(([key, pool]) => ({ key, pool }))
}

/** Every distinct, placeable (non-reference) library asset of a semantic type. */
export function pooledAssetsOfSemantic(semantic: string): LibraryAsset[] {
  const seen = new Set<string>()
  const out: LibraryAsset[] = []
  for (const pool of Object.values(pools)) {
    if (pool.semantic !== semantic || pool.referenceOnly) continue
    for (const e of pool.entries) {
      if (seen.has(e.id)) continue
      seen.add(e.id)
      const a = assetsById.get(e.id)
      if (a) out.push(a)
    }
  }
  return out
}

/**
 * Deterministically pick a library asset for a feature.
 * Same featureId → same asset; style narrows to a single pool when given
 * (falls back to a style-hashed pool choice when not).
 * Returns null when the tag has no pool — caller falls back to procgen.
 */
export function pickAssetFor(
  osmTag: string,
  featureId: string,
  style?: string,
): LibraryAsset | null {
  const candidates = poolsForTag(osmTag).filter(
    ({ pool }) => !pool.referenceOnly && (!style || pool.style === style),
  )
  if (!candidates.length) return null
  const { key, pool } =
    candidates[Math.floor(hash01(featureId + '|style') * candidates.length)]
  const entries = pool.entries.map(e => ({ value: e.id, weight: e.weight }))
  const id = pickWeighted(entries, hash01(featureId + '|' + key))
  return assetsById.get(id) ?? null
}

/**
 * Per-axis scale that fits an asset to a feature's real dimensions
 * (footprint x/z from OSM geometry, height y from tags), clamped so a
 * mis-tagged feature can't blow an asset up or shrink it to nothing.
 * Pass only the axes you know; unknown axes reuse the average known scale
 * to keep proportions.
 */
export function normalizeScale(
  asset: LibraryAsset,
  target: { x?: number; y?: number; z?: number },
  // Wide default: assets arrive at wildly different authoring scales (metric
  // Quaternius ~1×, non-metric Sketchfab up to ~1000×). The lower bound must
  // allow aggressive shrink-to-fit; the upper bound still guards a mis-tagged
  // OSM feature from exploding a correctly-scaled asset.
  clamp: [number, number] = [0.001, 4],
): { x: number; y: number; z: number } {
  const size = asset.sizeMeters
  if (!size) return { x: 1, y: 1, z: 1 }
  const known: number[] = []
  const axis = (t: number | undefined, s: number) => {
    if (t === undefined || s <= 0) return undefined
    const v = Math.min(clamp[1], Math.max(clamp[0], t / s))
    known.push(v)
    return v
  }
  const x = axis(target.x, size.x)
  const y = axis(target.y, size.y)
  const z = axis(target.z, size.z)
  const fallback = known.length ? known.reduce((a, b) => a + b, 0) / known.length : 1
  return { x: x ?? fallback, y: y ?? fallback, z: z ?? fallback }
}

/** Ground-plane offset after scaling: lift so bbox.min.y sits at y=0. */
export function groundOffset(asset: LibraryAsset, scaleY: number): number {
  return asset.groundOffsetY * scaleY
}

export function manifestCounts() {
  return manifest.counts as {
    assets: number
    pooled: number
    flaggedForReview: number
    pools: number
  }
}

// ---------------------------------------------------------------------------
// Curation studio data: group every placeable (non-reference) library model by
// a friendly "kind", with the per-model stats the studio shows so a human can
// pick the best (lightweight + compatible) variants for each thing.
// ---------------------------------------------------------------------------
const POOL_EXCLUDING = ['unclassified', 'no-geometry', 'high-poly']
// per-semantic triangle budget for a dense drivable city (mirrors the scanner's
// MAX_TRIS) — used to grade a model light / medium / heavy.
const TRI_BUDGET: Record<string, number> = {
  vegetation: 8000, street_furniture: 12000, barrier: 8000,
  landmark_prop: 45000, building: 100000, rooftop_prop: 10000,
}
// friendly kind grouping keyed by canonical kind → { label, procedural baseline note }.
const KIND_META: Record<string, { label: string; procedural: string }> = {
  tree: { label: '🌳 Trees / vegetation', procedural: 'Seeded procedural tree (species by climate/region)' },
  street_lamp: { label: '💡 Street lights', procedural: 'Procedural lamp post (region lamp style)' },
  bench: { label: '🪑 Benches', procedural: 'Procedural slatted bench' },
  bin: { label: '🚮 Bins', procedural: 'Procedural waste bin' },
  fountain: { label: '⛲ Fountains', procedural: 'Procedural basin fountain' },
  statue: { label: '🗿 Statues / memorials', procedural: 'Procedural plinth + figure stand-in' },
  fence: { label: '🚧 Fences / barriers', procedural: 'Procedural fence/wall run' },
  sign: { label: '🪧 Signs', procedural: 'Procedural sign panel (regulatory signs stay procedural)' },
  planter: { label: '🪴 Planters', procedural: 'Procedural concrete planter' },
  bollard: { label: '🚫 Bollards', procedural: 'Procedural bollard' },
  traffic_signal: { label: '🚦 Traffic signals', procedural: 'Procedural signal head + mast' },
  bus_stop: { label: '🚏 Bus stops', procedural: 'Procedural shelter' },
  fire_hydrant: { label: '🧯 Fire hydrants', procedural: 'Procedural hydrant' },
  manhole: { label: '🕳️ Manholes / drains', procedural: 'Procedural cover decal' },
  hvac: { label: '🌀 Rooftop HVAC', procedural: 'Procedural rooftop unit' },
  cone: { label: '🔶 Cones / temporary', procedural: 'Procedural traffic cone' },
  building: { label: '🏢 Buildings', procedural: 'Procedural extrusion + recognizer facade' },
}
// merge role-string variants across packs into one canonical kind.
const ROLE_ALIAS: Record<string, string> = {
  streetlight: 'street_lamp', street_light: 'street_lamp',
  'traffic-light': 'traffic_signal', traffic_light: 'traffic_signal', traffic_signals: 'traffic_signal',
  'trash-can': 'bin', trash_can: 'bin',
  'bus-stop': 'bus_stop',
  hydrant: 'fire_hydrant',
  drain: 'manhole',
  complete: 'building',
  barrier: 'fence',
}

export interface CurationCandidate {
  id: string
  name: string
  url: string            // served /assetlib URL for a live preview
  triangles: number
  bytes: number
  dims: { x: number; y: number; z: number } | null
  materials: number
  textures: number
  weightClass: 'light' | 'medium' | 'heavy'
  recommended: boolean   // light + not oversized → a good default keep
  flags: string[]
  source: string
  license: string
  semantic: string
  role: string
  osmTags: string[]
}
export interface CurationKind {
  kind: string
  label: string
  procedural: string
  candidates: CurationCandidate[]
}

function assetUrl(path: string): string {
  return '/assetlib/' + path.replace(/^assets\/library\//, '')
}

/** All placeable library models grouped by kind, richest-first, with stats. */
export function curationCandidates(): CurationKind[] {
  const placeable = (manifest.assets as LibraryAsset[]).filter(
    (a) =>
      !a.flags.some((f) => POOL_EXCLUDING.includes(f)) &&
      !a.referenceOnly &&
      a.semantic !== 'building_module' &&
      a.semantic !== 'road_module' &&
      a.semantic !== 'road_decal' &&
      a.semantic !== 'sidewalk_module' &&
      (a.osmTags.length > 0 || a.internalTags.length > 0),
  )
  const byKind = new Map<string, CurationCandidate[]>()
  for (const a of placeable) {
    const kind = ROLE_ALIAS[a.role] ?? (KIND_META[a.role] ? a.role : a.role || a.semantic)
    const budget = TRI_BUDGET[a.semantic] ?? 12000
    const weightClass = a.triangles <= budget * 0.34 ? 'light' : a.triangles <= budget ? 'medium' : 'heavy'
    const cand: CurationCandidate = {
      id: a.id,
      name: a.id.split('/').pop() ?? a.id,
      url: assetUrl(a.path),
      triangles: a.triangles,
      bytes: a.bytes ?? 0,
      dims: a.sizeMeters,
      materials: a.materials?.length ?? 0,
      textures: a.textures?.length ?? 0,
      weightClass,
      recommended: weightClass === 'light' && !a.flags.includes('oversized'),
      flags: a.flags,
      source: a.source,
      license: a.license,
      semantic: a.semantic,
      role: a.role,
      osmTags: a.osmTags,
    }
    if (!byKind.has(kind)) byKind.set(kind, [])
    byKind.get(kind)!.push(cand)
  }
  return [...byKind.entries()]
    .map(([kind, candidates]) => ({
      kind,
      label: KIND_META[kind]?.label ?? kind,
      procedural: KIND_META[kind]?.procedural ?? 'Procedural stand-in',
      candidates: candidates.sort((a, b) => a.triangles - b.triangles), // lightest first
    }))
    .sort((a, b) => b.candidates.length - a.candidates.length)
}
