// Asset library pools — bridges assets/manifest.json into the Context Resolver.
//
// The manifest is generated by `node tools/build-asset-manifest.mjs` from the
// scanned library. Selection follows the same determinism contract as the rest
// of the resolver: hash01(featureId + poolKey) → pickWeighted, so an OSM
// feature always resolves to the same asset, but neighboring features vary.

import manifest from '../../assets/manifest.json'
import { hash01, pickWeighted } from './resolve'

export interface LibraryAsset {
  id: string
  path: string
  semantic: string
  role: string
  style: string
  osmTags: string[]
  internalTags: string[]
  referenceOnly: boolean
  sizeMeters: { x: number; y: number; z: number } | null
  groundOffsetY: number
  triangles: number
  lods: string[]
  source: string
  license: string
  flags: string[]
}

interface Pool {
  osmTag: string
  style: string
  semantic: string
  referenceOnly: boolean
  // normalizeScale:true marks a non-metric source asset that must be scaled to
  // real bounds on placement (see normalizeScale / the wide default clamp).
  entries: { id: string; weight: number; normalizeScale?: boolean }[]
}

const assetsById = new Map<string, LibraryAsset>(
  (manifest.assets as LibraryAsset[]).map(a => [a.id, a]),
)
const pools = manifest.pools as Record<string, Pool>

export function libraryAsset(id: string): LibraryAsset | undefined {
  return assetsById.get(id)
}

/** All pools that can satisfy an OSM tag (one per style). */
export function poolsForTag(osmTag: string): { key: string; pool: Pool }[] {
  return Object.entries(pools)
    .filter(([, p]) => p.osmTag === osmTag)
    .map(([key, pool]) => ({ key, pool }))
}

/**
 * Deterministically pick a library asset for a feature.
 * Same featureId → same asset; style narrows to a single pool when given
 * (falls back to a style-hashed pool choice when not).
 * Returns null when the tag has no pool — caller falls back to procgen.
 */
export function pickAssetFor(
  osmTag: string,
  featureId: string,
  style?: string,
): LibraryAsset | null {
  const candidates = poolsForTag(osmTag).filter(
    ({ pool }) => !pool.referenceOnly && (!style || pool.style === style),
  )
  if (!candidates.length) return null
  const { key, pool } =
    candidates[Math.floor(hash01(featureId + '|style') * candidates.length)]
  const entries = pool.entries.map(e => ({ value: e.id, weight: e.weight }))
  const id = pickWeighted(entries, hash01(featureId + '|' + key))
  return assetsById.get(id) ?? null
}

/**
 * Per-axis scale that fits an asset to a feature's real dimensions
 * (footprint x/z from OSM geometry, height y from tags), clamped so a
 * mis-tagged feature can't blow an asset up or shrink it to nothing.
 * Pass only the axes you know; unknown axes reuse the average known scale
 * to keep proportions.
 */
export function normalizeScale(
  asset: LibraryAsset,
  target: { x?: number; y?: number; z?: number },
  // Wide default: assets arrive at wildly different authoring scales (metric
  // Quaternius ~1×, non-metric Sketchfab up to ~1000×). The lower bound must
  // allow aggressive shrink-to-fit; the upper bound still guards a mis-tagged
  // OSM feature from exploding a correctly-scaled asset.
  clamp: [number, number] = [0.001, 4],
): { x: number; y: number; z: number } {
  const size = asset.sizeMeters
  if (!size) return { x: 1, y: 1, z: 1 }
  const known: number[] = []
  const axis = (t: number | undefined, s: number) => {
    if (t === undefined || s <= 0) return undefined
    const v = Math.min(clamp[1], Math.max(clamp[0], t / s))
    known.push(v)
    return v
  }
  const x = axis(target.x, size.x)
  const y = axis(target.y, size.y)
  const z = axis(target.z, size.z)
  const fallback = known.length ? known.reduce((a, b) => a + b, 0) / known.length : 1
  return { x: x ?? fallback, y: y ?? fallback, z: z ?? fallback }
}

/** Ground-plane offset after scaling: lift so bbox.min.y sits at y=0. */
export function groundOffset(asset: LibraryAsset, scaleY: number): number {
  return asset.groundOffsetY * scaleY
}

export function manifestCounts() {
  return manifest.counts as {
    assets: number
    pooled: number
    flaggedForReview: number
    pools: number
  }
}
