#!/usr/bin/env node
// Bundle the World API endpoints into self-contained ESM functions under api/.
//
// Why: this repo uses extensionless ESM imports ("type": "module"), which
// Vercel's per-file TS transpile can't resolve at runtime (ERR_MODULE_NOT_FOUND
// for '../_lib/world'). Bundling each endpoint with esbuild removes every
// relative import; bare node_modules imports stay external so Vercel's file
// tracing still packages native deps (@napi-rs/canvas, draco wasm) correctly.
//
// Output is COMMITTED (api/v1/maps/*.mjs) and also rebuilt by `npm run build`,
// so git-based deploys stay fresh even if the function build runs first.

import { build } from 'esbuild'

const shared = {
  bundle: true,
  platform: 'node',
  format: 'esm',
  target: 'node20',
  packages: 'external',
  legalComments: 'none',
  banner: { js: '// GENERATED by tools/build-api.mjs — edit src/server/* instead.\n' },
  logLevel: 'info',
}

await build({ ...shared, entryPoints: ['src/server/mapsPost.ts'], outfile: 'api/v1/maps/index.mjs' })
await build({ ...shared, entryPoints: ['src/server/mapsGet.ts'], outfile: 'api/v1/maps/[id].mjs' })
