// GENERATED by tools/build-api.mjs — edit src/server/* instead.


// src/server/world.ts
import { list, put } from "@vercel/blob";
var JOB_STALE_MS = 15 * 60 * 1e3;
function corsHeaders() {
  return {
    "access-control-allow-origin": process.env.WORLD_API_CORS_ORIGIN ?? "*",
    "access-control-allow-methods": "GET, POST, OPTIONS",
    "access-control-allow-headers": "content-type, x-api-key",
    "access-control-max-age": "86400"
  };
}
function authorized(req) {
  const keys = (process.env.WORLD_API_KEYS ?? "").split(",").map((k) => k.trim()).filter(Boolean);
  if (!keys.length) return true;
  return keys.includes(req.headers.get("x-api-key") ?? "");
}
function json(status, value) {
  return new Response(JSON.stringify(value, null, 2), {
    status,
    headers: { "content-type": "application/json", ...corsHeaders() }
  });
}
async function findBlob(pathname) {
  const res = await list({ prefix: pathname, limit: 1 });
  const hit = res.blobs.find((b) => b.pathname === pathname);
  return hit ? { url: hit.url, uploadedAt: new Date(hit.uploadedAt) } : null;
}
var manifestPath = (id) => `maps/${id}/manifest.json`;
var jobPath = (id) => `jobs/${id}.json`;
var failedPath = (id) => `jobs/${id}.failed.json`;
async function jobStatus(id) {
  const manifest = await findBlob(manifestPath(id));
  if (manifest) {
    const res = await fetch(manifest.url);
    return { status: "ready", manifest: await res.json() };
  }
  const [job, failed] = await Promise.all([findBlob(jobPath(id)), findBlob(failedPath(id))]);
  if (job && (!failed || job.uploadedAt > failed.uploadedAt)) {
    return {
      status: "generating",
      startedAt: job.uploadedAt.toISOString(),
      stale: Date.now() - job.uploadedAt.getTime() > JOB_STALE_MS
    };
  }
  if (failed) {
    const res = await fetch(failed.url, { cache: "no-store" });
    const rec = await res.json().catch(() => ({}));
    return { status: "failed", error: rec.error ?? "generation failed", failedAt: failed.uploadedAt.toISOString() };
  }
  return { status: "unknown" };
}

// src/server/mapsGet.ts
async function OPTIONS() {
  return new Response(null, { status: 204, headers: corsHeaders() });
}
async function GET(request) {
  if (!authorized(request)) return json(401, { error: "missing or invalid x-api-key" });
  const id = new URL(request.url).pathname.split("/").pop() ?? "";
  if (!/^[0-9a-f]{16}$/.test(id)) return json(400, { error: "invalid map id" });
  const status = await jobStatus(id);
  switch (status.status) {
    case "ready":
      return json(200, { id, status: "ready", manifest: status.manifest });
    case "generating":
      return json(200, {
        id,
        status: status.stale ? "stalled" : "generating",
        startedAt: status.startedAt,
        note: status.stale ? "No progress for 15+ min \u2014 re-POST the same bbox/options to retry." : void 0
      });
    case "failed":
      return json(200, { id, status: "failed", error: status.error, failedAt: status.failedAt });
    default:
      return json(404, { id, status: "unknown", note: "No job with this id \u2014 POST /api/v1/maps first." });
  }
}
export {
  GET,
  OPTIONS
};
